//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvcProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKulüpler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKulüpler()
        {
            this.TblOgrenciler = new HashSet<TblOgrenciler>();
        }
    
        public byte KulüpId { get; set; }
        public string KulüpAd { get; set; }
        public Nullable<short> KulüpKont { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOgrenciler> TblOgrenciler { get; set; }
    }
}
